---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: licenses, licensing, subscriptions, annual subscription, paygo, hourly subscription, bluexp 
summary: Es gibt zwei Möglichkeiten, nach Ablauf Ihrer 14-tägigen kostenlosen Testversion für Synchronisierungsbeziehungen zu bezahlen.  Die erste Möglichkeit besteht darin, bei AWS oder Azure ein Abonnement mit nutzungsbasierter oder jährlicher Zahlung abzuschließen.  Die zweite Möglichkeit besteht darin, Lizenzen direkt von NetApp zu erwerben. 
---
= Lizenzierungsübersicht für NetApp Copy and Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach Ablauf Ihrer 14-tägigen kostenlosen Testversion gibt es zwei Möglichkeiten, für NetApp Copy- und Sync-Beziehungen zu bezahlen.  Die erste Möglichkeit besteht darin, bei AWS oder Azure ein Abonnement mit nutzungsbasierter oder jährlicher Zahlung abzuschließen.  Die zweite Möglichkeit besteht darin, Lizenzen direkt von NetApp zu erwerben.

Lizenzen sollten über NetApp Copy and Sync oder die entsprechende Website und *nicht* über die NetApp -Konsole verwaltet werden.



== Marktplatz-Abonnement

Wenn Sie Copy and Sync von AWS oder Azure abonnieren, können Sie stundenweise oder jährlich bezahlen. link:task-licensing.html["Sie können entweder über AWS oder Azure abonnieren"] , je nachdem, wo Sie die Rechnung erhalten möchten.



=== Stundenabonnement

Bei einem stündlichen Pay-as-you-go-Abonnement werden Ihnen stündlich Gebühren basierend auf der Anzahl der von Ihnen erstellten Synchronisierungsbeziehungen berechnet.

* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Preise in Azure anzeigen"^]
* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["Pay-as-you-go-Preise in AWS anzeigen"^]




=== Jahresabonnement

Ein Jahresabonnement bietet eine Lizenz für 20 Synchronisierungsbeziehungen, die Sie im Voraus bezahlen.  Wenn Sie über 20 Synchronisierungsbeziehungen hinausgehen und über AWS abonniert haben, zahlen Sie für die zusätzlichen Beziehungen stundenweise.

https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Jährliche Preise in AWS anzeigen"^]



== Lizenzen von NetApp

Eine weitere Möglichkeit, Synchronisierungsbeziehungen im Voraus zu bezahlen, besteht darin, Lizenzen direkt von NetApp zu erwerben.  Mit jeder Lizenz können Sie bis zu 20 Synchronisierungsbeziehungen erstellen.

Sie können diese Lizenzen mit einem AWS- oder Azure-Abonnement verwenden.  Wenn Sie beispielsweise über 25 Synchronisierungsbeziehungen verfügen, können Sie für die ersten 20 Synchronisierungsbeziehungen eine Lizenz verwenden und dann für die restlichen 5 Synchronisierungsbeziehungen eine nutzungsabhängige Bezahlung von AWS oder Azure vornehmen.

link:task-licensing.html["Erfahren Sie, wie Sie Lizenzen erwerben und zu NetApp Copy and Sync hinzufügen"] .



=== Lizenzbedingungen

Kunden, die eine Bring Your Own License (BYOL) zum Kopieren und Synchronisieren erwerben, sollten sich der mit der Lizenzberechtigung verbundenen Einschränkungen bewusst sein.

* Kunden sind berechtigt, die BYOL-Lizenz für einen Zeitraum von höchstens einem Jahr ab dem Lieferdatum zu nutzen.
* Kunden sind berechtigt, die BYOL-Lizenz zu nutzen, um insgesamt nicht mehr als 20 einzelne Verbindungen zwischen einer Quelle und einem Ziel (jeweils eine „Synchronisierungsbeziehung“) herzustellen.
* Der Anspruch eines Kunden erlischt mit Ablauf der einjährigen Lizenzlaufzeit, unabhängig davon, ob der Kunde die Beschränkung auf 20 Synchronisierungsbeziehungen erreicht hat.
* Falls der Kunde sich für eine Verlängerung seiner Lizenz entscheidet, werden nicht genutzte Synchronisierungsbeziehungen aus der vorherigen Lizenzerteilung NICHT auf die Lizenzverlängerung übertragen.

