---
sidebar: sidebar 
permalink: concept-privacy.html 
keywords: privacy, data privacy, credentials, access to credentials, hashicorp vault 
summary: NetApp hat keinen Zugriff auf die Anmeldeinformationen, die Sie bei der Verwendung von NetApp Copy and Sync angeben.  Die Anmeldeinformationen werden direkt auf dem Computer des Datenbrokers gespeichert, der sich in Ihrem Netzwerk befindet. 
---
= Datenschutz in NetApp Copy and Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp hat keinen Zugriff auf die Anmeldeinformationen, die Sie bei der Verwendung von NetApp Copy and Sync angeben.  Die Anmeldeinformationen werden direkt auf dem Computer des Datenbrokers gespeichert, der sich in Ihrem Netzwerk befindet.

Abhängig von der von Ihnen gewählten Konfiguration werden Sie beim Erstellen einer neuen Beziehung möglicherweise von Copy and Sync zur Eingabe von Anmeldeinformationen aufgefordert.  Beispielsweise beim Einrichten einer Beziehung, die einen SMB-Server umfasst, oder beim Bereitstellen des Datenbrokers in AWS.

Diese Anmeldeinformationen werden immer direkt beim Datenbroker selbst gespeichert.  Der Datenbroker befindet sich auf einer Maschine in Ihrem Netzwerk, unabhängig davon, ob diese sich vor Ort oder in Ihrem Cloud-Konto befindet.  Die Anmeldeinformationen werden NetApp niemals zur Verfügung gestellt.

Die Anmeldeinformationen werden lokal auf dem Computer des Datenbrokers mit HashiCorp Vault verschlüsselt.
